# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20170313_1220'),
        ('ipn', '0007_auto_20160219_1135'),
        ('userprofiles', '0001_initial'),
        ('sermepa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ok', 'Success'), ('err', 'Error'), ('ser', 'Signature error'), ('pen', 'Pending')], max_length=3)),
                ('payment_type', models.CharField(choices=[('pyp', 'Paypal'), ('rsy', 'Redsys'), ('zvl', 'Zero value')], editable=False, max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message for error status')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofiles.CheckoutPromoCode')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.Order')),
                ('paypal_response', models.ForeignKey(blank=True, help_text='Response for paypal payments', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipn.PayPalIPN')),
                ('sermepa_response', models.ForeignKey(blank=True, help_text='Response for redsys payments', null=True, on_delete=django.db.models.deletion.CASCADE, to='sermepa.SermepaResponse')),
            ],
            managers=[
                ('paypal', django.db.models.manager.Manager()),
            ],
        ),
    ]
