# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lafiambrera_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OneEuro', models.IntegerField()),
            ],
        ),
    ]
