# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170706_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[(b'pyp', b'Paypal'), (b'rsy', b'Redsys'), (b'zvl', b'Zero value')], default=b'zbl', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(b'ok', b'Success'), (b'err', b'Error'), (b'ser', b'Signature error'), (b'pen', b'Pending')], default=b'pen', max_length=3),
        ),
    ]
