# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0007_auto_20160219_1135'),
        ('sermepa', '0001_initial'),
        ('payments', '0004_auto_20170720_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'ok', b'Success'), (b'err', b'Error'), (b'ser', b'Signature error'), (b'pen', b'Pending')], default=b'pen', max_length=3)),
                ('payment_type', models.CharField(choices=[(b'pyp', b'Paypal'), (b'rsy', b'Redsys'), (b'zvl', b'Zero value')], default=b'zbl', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('error_message', models.TextField(blank=True, help_text=b'Error message for error status')),
            ],
            managers=[
                ('paypal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='moneytowallet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='walletpayment',
            name='moneytowallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.MoneyToWallet'),
        ),
        migrations.AddField(
            model_name='walletpayment',
            name='paypal_response',
            field=models.ForeignKey(blank=True, help_text=b'Response for paypal payments', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipn.PayPalIPN'),
        ),
        migrations.AddField(
            model_name='walletpayment',
            name='sermepa_response',
            field=models.ForeignKey(blank=True, help_text=b'Response for redsys payments', null=True, on_delete=django.db.models.deletion.CASCADE, to='sermepa.SermepaResponse'),
        ),
    ]
