# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20170720_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalPaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payfor', models.CharField(max_length=20, null=True, verbose_name=b'Payment For')),
                ('payuiid', models.CharField(max_length=200, verbose_name=b'Payment UIID')),
                ('paypal_paymentid', models.CharField(max_length=200, verbose_name=b'Paypal Payment ID')),
                ('paypal_token', models.CharField(max_length=200, null=True, verbose_name=b'Paypal Transaction Token')),
                ('payer_id', models.CharField(max_length=200, null=True, verbose_name=b'Customer Paypal ID')),
                ('status', models.BooleanField(default=False, verbose_name=b'Status')),
            ],
        ),
    ]
