# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paypalpaymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletpayment',
            name='moneytowallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.MoneyToWallet'),
        ),
    ]
