# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_walletorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[(b'pyp', b'Paypal'), (b'rsy', b'Redsys'), (b'wlt', b'Wallet'), (b'zvl', b'Zero value')], default=b'zbl', max_length=3),
        ),
        migrations.AlterField(
            model_name='walletorder',
            name='paymentgateway',
            field=models.FloatField(max_length=20, null=True, verbose_name=b'Payment Gateway'),
        ),
        migrations.AlterField(
            model_name='walletpayment',
            name='payment_type',
            field=models.CharField(choices=[(b'pyp', b'Paypal'), (b'rsy', b'Redsys'), (b'wlt', b'Wallet'), (b'zvl', b'Zero value')], default=b'zbl', max_length=3),
        ),
    ]
