# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20170725_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='lafiambera_credit',
            field=models.FloatField(default=0.0),
        ),
    ]
