# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=100)),
                ('lang_name', models.CharField(max_length=100)),
            ],
        ),
    ]
