# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='static/mainapp/uploads'),
        ),
    ]
