# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170608_0720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
