# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_checkoutcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
