# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_paywallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayWallet',
        ),
    ]
