# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20170812_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviterequest',
            name='uiid',
        ),
        migrations.AddField(
            model_name='inviterequest',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
