# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0020_auto_20170814_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.IntegerField(null=True, verbose_name='Reciever ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Time')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
