# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_shareselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareselection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ShareSelection', verbose_name='Share Selection')),
            ],
        ),
    ]
