# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_selectionreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionreference',
            name='lunchbox_id',
            field=models.IntegerField(null=True, verbose_name='Lunchbox ID'),
        ),
    ]
