# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_selectionreference_lunchbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareselection',
            name='credits',
            field=models.FloatField(null=True, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='cat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='share_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
