# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20170822_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
