# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20170919_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontent',
            old_name='content',
            new_name='msg',
        ),
    ]
