# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20170919_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='msg',
        ),
    ]
