# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
