# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 10:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20170703_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
