# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_lunchsteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchsteps',
            name='title',
            field=models.CharField(default='Steps to a healthy lunch', max_length=200),
        ),
    ]
