# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 11:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_lunchsteps_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchsteps',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
