# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 12:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchsteps',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='lunchsteps',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='lunchsteps',
            name='title_en',
            field=models.CharField(default='Steps to a healthy lunch', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lunchsteps',
            name='title_es',
            field=models.CharField(default='Steps to a healthy lunch', max_length=200, null=True),
        ),
    ]
