# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170704_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBenifits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('head', models.CharField(max_length=200, verbose_name='Headings')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
