# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_groupbenifits'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbenifits',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupbenifits',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='groupbenifits',
            name='head_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Headings'),
        ),
        migrations.AddField(
            model_name='groupbenifits',
            name='head_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Headings'),
        ),
        migrations.AddField(
            model_name='groupbenifits',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='groupbenifits',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
