# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20170809_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbenifits',
            name='title',
            field=models.CharField(max_length=11, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='groupbenifits',
            name='title_en',
            field=models.CharField(max_length=11, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='groupbenifits',
            name='title_es',
            field=models.CharField(max_length=11, null=True, verbose_name='Title'),
        ),
    ]
