# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_supportdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbenifits',
            name='content',
            field=models.TextField(default='No data available', verbose_name='Popup Content'),
        ),
    ]
