# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_groupbenifits_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbenifits',
            name='content_en',
            field=models.TextField(default='No data available', null=True, verbose_name='Popup Content'),
        ),
        migrations.AddField(
            model_name='groupbenifits',
            name='content_es',
            field=models.TextField(default='No data available', null=True, verbose_name='Popup Content'),
        ),
    ]
