# -*- coding: utf-8 -*-

"""
Django settings for restaurant project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from django.utils.translation import ugettext_lazy as _
from django.contrib.messages import ERROR
import os
import sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(8g$a(0er4t_@r2ku)w=j%_%p(*3a)b3!0k*h*ry*286*0uqx@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG404 = True
ALLOWED_HOSTS = ['*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',
    'django_cleanup',
    'nested_inline',
    'django.contrib.sites',
    'django_extensions',
    'paypal.standard.ipn',
    'sermepa',
    'userprofiles',
    'orders',
    'restaurant',
    'payments',
    'easycart',
    'cart',
    'mainapp',
    'pages',
    'ckeditor',
    'simple_pagination',
    'django_blog_it.django_blog_it',
    'login_register',
    'dashboard',
    'carthandler',
    'mails',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin',
    'django_bootstrap_breadcrumbs',
    
]
EASYCART_CART_CLASS = 'cart.views.Cart'

PAYPAL_TEST = True

AUTHENTICATION_BACKENDS = (
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)




SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email'],
        'AUTH_PARAMS': {},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v2.4',
    }
}

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'restaurant/templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'easycart.context_processors.cart',
                'django.template.context_processors.i18n',
                'mainapp.context_processors.categories',

            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
#psql -U lafiambrerauser lafiambrera_db < /var/www/html/python/hanna/lafiambrera/2017.pgsql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lafiambrera_db',
        'USER': 'lafiambrerauser',
        'PASSWORD': 'esfera',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

BASE_URL="http://138.68.136.81:9002/"
SECOND_URL="http://138.68.136.81:9000/"
# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'
DEFAULT_CHARSET = 'utf-8'
#TIME_ZONE =  'Asia/Kolkata'
# TIME_ZONE = 'CET'
TIME_ZONE = 'CET'
USE_I18N = True

USE_L10N = True

USE_TZ = True

SOLID_I18N_USE_REDIRECTS = False
SOLID_I18N_HANDLE_DEFAULT_PREFIX = False
SOLID_I18N_DEFAULT_PREFIX_REDIRECT = False

LANGUAGES = (
    ('en',  _('English')),
    ('es',  _(u'Español')),
)
MODELTRANSLATION_LANGUAGES = ('en', 'es')
MODELTRANSLATION_TRANSLATION_FILES = (
    'mainapp.translation',
  
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

MULTILINGUAL_FAIL_SILENTLY = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, '../static/')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
)
MEDIA_ROOT = os.path.join(BASE_DIR, './media/')
MEDIA_URL = '/media/'

# Easy thumbnails:
##################
# Set short hashed filename like 1xedFtqllFo9.jpg
THUMBNAIL_NAMER = 'easy_thumbnails.namers.hashed'
THUMBNAIL_ALIASES = {
    '': {
        'restaurant_logo': {'size': (290, 100), 'crop': True},
        'restaurant_logo_dash_home': {'size': (235, 140), 'crop': True},
        'restaurant_control_logo': {'size': (315, 140), 'crop': True},
        'restaurant_control_logo_admin': {'size': (263, 150), 'crop': True},
        'restaurant_control_logo_small': {'size': (165, 70), 'crop': True},
        'restaurant_gallery_image': {'size': (748, 434), 'crop': True},
        'gallery_image': {'size': (780, 500), 'crop': True},
        'normal_lb_big': {'size': (800, 185), 'crop': False},
        'normal_lb_small': {'size': (49, 44), 'crop': True},
        'small_lb_big': {'size': (209, 80), 'crop': True},
        'small_lb_small': {'size': (69, 30), 'crop': True},
        'lb_privilege': {'size': (135, 50), 'crop': True},
        'profile_lb_big': {'size': (263, 150), 'crop': True},
        'profile_lb_small': {'size': (87, 75), 'crop': True},
        'cart_lb_big': {'size': (325, 175), 'crop': True},
        'control_image_big': {'size': (333, 150), 'crop': True},
        'control_image_small': {'size': (250, 80), 'crop': True},
        'control_lb_privilege': {'size': (150, 48), 'crop': True},
        'control_restaurant_gallery_big': {'size': (500, 215), 'crop': True},
        'control_restaurant_gallery_small': {'size': (400, 100), 'crop': True},
        'control_restaurant_logo': {'size': (400, 134), 'crop': True},
        'home_lunchbox_pic':{'size':(360,230), 'crop':True},
        'dashboard_lunchbox':{'size':(360,290), 'crop':True},
        'group_benifits':{'size':(768,576), 'crop':True},
    }
}
THUMBNAIL_PRESERVE_EXTENSIONS = True

SITE_ID = 1
# SITE_URL = 'https://lafiambrera.cat'
SITE_URL ='http://138.68.136.81:9002/'
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/en/customer/profile/1/'
ACCOUNT_EMAIL_VERIFICATION = "none"

MESSAGE_LEVEL = ERROR

# === DJANGO_SES ========================================================
INSTALLED_APPS.append('django_ses')



EMAIL_BACKEND = 'django_ses.SESBackend'
# These are optional — if they're set as environment variables they won't
# need to be set here as well
# AWS_SES_ACCESS_KEY_ID = 'AKIAJG4GTAO2CXEVCQJQ'
# AWS_SES_SECRET_ACCESS_KEY = 'Aodv4l8Li/V4Q3lYTVIpKV152Tk5u2tWIHjqzsUBen3D'

AWS_ACCESS_KEY_ID = 'AKIAJRQGJOVZ3PQZ36WA'
AWS_SECRET_ACCESS_KEY = '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'


# Additionally, if you are not using the default AWS region of us-east-1,
# you need to specify a region, like so:
# AWS_SES_REGION_NAME = 'eu-west-1'
# AWS_SES_REGION_ENDPOINT = 'email.eu-west-1.amazonaws.com'

# EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
# EMAIL_HOST_USER = "noreply@lafiambrera.cat"
# EMAIL_HOST = '52.59.237.138'
# EMAIL_PORT = 465
#Gmail Smtp mail detail
EMAIL_ADDRESS = "itsmepython21@gmail.com"
PASSWORD = "esfera0143"
# === CSRF ==============================================================
# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_HTTPONLY = True
# CSRF_TRUSTED_ORIGINS = 'sub-docker-dev.eu-central-1.elasticbeanstalk.com'
CSRF_FAILURE_VIEW = 'restaurant.views.csrf_failure'


# === LOGS ==============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s][%(name)s] %(levelname)s %(message)s',
            'datefmt': "%Y-%m-%d %H:%M:%S",
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'stderr': {
            'level': 'ERROR',
            'formatter': 'verbose',
            'class':'logging.StreamHandler',
            'stream': sys.stderr,
        },
        'stdout': {
            'level': 'INFO',
            'formatter': 'verbose',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
    },
    'loggers': {
        '': {
            'handlers': ['stdout'],
            'level': 'DEBUG',
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}


# Sermepa settings (RedSys)

SERMEPA_URL_PRO = 'https://sis.redsys.es/sis/realizarPago'
SERMEPA_URL_TEST = 'https://sis-t.redsys.es:25443/sis/realizarPago'
SERMEPA_MERCHANT_CODE = '335992137'  # test code
SERMEPA_TERMINAL = "1"
SERMEPA_SECRET_KEY = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7'
SERMEPA_BUTTON_IMG = '{}img/visa-button.png'.format(STATIC_URL)
SERMEPA_BUTTON_TEXT = "La caixa"
SERMEPA_CURRENCY = '978'  # Euros
# SERMEPA_IPN = "https://lafiambrera.cat/sermepa/"
SERMEPA_IPN = "http://138.68.136.81:9002/sermepa/"
SERMEPA_SIGNATURE_VERSION = "HMAC_SHA256_V1"
# Paypal settings
#---------------------------------Paypal original details
# PAYPAL_EMAIL = "am@mohoparty.com"
# PAYMENT_RETURN_URL = "https://lafiambrera.cat/enjoy_your_box/?order-uuid={0}"
# PAYMENT_CANCEL_RETURN = "https://lafiambrera.cat/cart/"
# PAYPAL_NOTIFY_URL = "https://lafiambrera.cat/paypal/"

# PAYPAL_EMAIL = "aman_katoch@esferasoft.com"
PAYMENT_RETURN_URL = "http://138.68.136.81:9002/confirm/visa/payment/?order-uuid={0}"
PAYMENT_CANCEL_RETURN = "http://138.68.136.81:9002/checkout/"
# PAYPAL_NOTIFY_URL = "http://138.68.136.81:9002/paypal/"


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'allowedContent': True,
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline','Font','FontSize'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
            ["Image", "Table", "Anchor", "SectionLink", "Subscript", "Superscript"], ['Undo', 'Redo'],
        ]
    }
}
DATA_UPLOAD_MAX_MEMORY_SIZE = 10242880
# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'




