# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-04 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TextField(null=True, verbose_name='Opening hours'),
        ),
    ]
