# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_restaurant_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbox',
            name='useless_date',
            field=models.DateField(blank=True, null=True, verbose_name='Useless_date'),
        ),
        migrations.AddField(
            model_name='lunchbox',
            name='useless_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Useless_time'),
        ),
    ]
