# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_language'),
        ('userprofiles', '0003_auto_20170422_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbox',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name=b'lunchbox category'),
        ),
    ]
