# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20170701_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchbox',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='lunchbox',
            name='desc_es',
        ),
        migrations.RemoveField(
            model_name='lunchbox',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='lunchbox',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='desc_es',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name_es',
        ),
    ]
