# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_auto_20170703_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbox',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Name of lunchbox'),
        ),
        migrations.AddField(
            model_name='lunchbox',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Name of lunchbox'),
        ),
    ]
