# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_auto_20170703_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='desc_en',
            field=models.TextField(null=True, verbose_name=b'Short description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='desc_es',
            field=models.TextField(null=True, verbose_name=b'Short description'),
        ),
    ]
