# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_auto_20170703_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(blank=True, default=b'Spain', max_length=50, null=True, verbose_name=b'Country'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(blank=True, default=b'Unknown', max_length=50, null=True, verbose_name=b'Street'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, default=b'Barcelona', max_length=50, null=True, verbose_name=b'City'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, default=b'Catalonia', max_length=50, null=True, verbose_name=b'State'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Zip code'),
        ),
    ]
