# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0011_auto_20170707_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Country'),
        ),
    ]
