# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 06:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0015_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchbox',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='desc_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='desc_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
