# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0016_auto_20170729_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytext', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
