# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0017_testingtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingTable',
        ),
    ]
