# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0018_delete_testingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchbox',
            name='vat',
            field=models.FloatField(null=True, verbose_name=b'Vat'),
        ),
    ]
