# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0019_lunchbox_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchbox',
            name='vat',
            field=models.FloatField(default=0, null=True, verbose_name=b'Vat'),
        ),
    ]
