# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0021_profile_accounts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='building_num',
            field=models.IntegerField(default=0, verbose_name=b'Building Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='door_num',
            field=models.IntegerField(default=0, verbose_name=b'Door Number'),
        ),
    ]
