# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0024_auto_20170905_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunchbox',
            name='useless_date',
        ),
        migrations.RemoveField(
            model_name='lunchbox',
            name='useless_time',
        ),
    ]
