# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0025_auto_20170906_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='building_num',
            field=models.TextField(blank=True, null=True, verbose_name=b'Building Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='door_num',
            field=models.TextField(blank=True, null=True, verbose_name=b'Door Number'),
        ),
    ]
