# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0026_auto_20170906_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default=b'Catalonia', max_length=50, null=True, verbose_name=b'State full'),
        ),
    ]
