# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0028_auto_20170920_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchbox',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Carbohydrates (Gr)'),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Fat (Gr)'),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='protein',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Protein (Gr)'),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='sodium',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Sodium (Mgr)'),
        ),
        migrations.AlterField(
            model_name='lunchbox',
            name='sugar',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Sugar (Gr)'),
        ),
        migrations.AlterField(
            model_name='restaurantdiscountcoupon',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Percent'),
        ),
    ]
