# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_catering', models.BooleanField(default=False, verbose_name='Is catering basket?')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('u_is_processing', models.BooleanField(default=False, verbose_name='Is processing?')),
                ('u_processing_date_from', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Processing start date')),
                ('u_processing_date_till', models.DateField(blank=True, default=datetime.datetime(2017, 3, 20, 11, 20, 46, 412732, tzinfo=utc), null=True, verbose_name='Processing till date')),
                ('u_is_payment_requested', models.BooleanField(default=False, verbose_name='Payment requested?')),
                ('u_payment_requested_date', models.DateField(blank=True, null=True, verbose_name='Payment requested date')),
                ('u_is_confirmed_by_lf', models.BooleanField(default=False, verbose_name='Is confirmed by LaFiambrera?')),
                ('u_is_confirmed_by_lf_date', models.DateField(blank=True, null=True, verbose_name='Confirmed by LaFiambrera date')),
                ('u_is_paid', models.BooleanField(default=False, verbose_name='Is paid?')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='Is highlighted?')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is archived?')),
                ('is_catering', models.BooleanField(default=False, verbose_name='This is catering order?')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Order created date')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('delivery_date', models.DateTimeField(null=True, verbose_name='Date and time of delivery')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is processed?')),
                ('processed_date', models.DateField(blank=True, null=True, verbose_name='Processed date')),
                ('is_payment_requested', models.BooleanField(default=False, verbose_name='Payment requested?')),
                ('payment_request_date', models.DateField(blank=True, null=True, verbose_name='Payment request date')),
                ('is_confirmed_by_lf', models.BooleanField(default=False, verbose_name='Is confirmed by LaFiambrera?')),
                ('confirmation_by_lf_date', models.DateField(blank=True, null=True, verbose_name='Confirmation by LaFiambrera date')),
                ('is_payment_transferred', models.BooleanField(default=False, verbose_name='Is transferred?')),
                ('payment_transfer_date', models.DateField(blank=True, null=True, verbose_name='Transfer date')),
            ],
        ),
    ]
