# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170404_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 28, 9, 50, 21, 434145, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
