# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 03:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170421_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 29, 3, 44, 36, 683413, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
