# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170422_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 4, 29, 4, 1, 42, 126323, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
