# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170511_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 25, 5, 55, 17, 504079, tzinfo=utc), null=True, verbose_name=b'Processing till date'),
        ),
    ]
