# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20170607_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 14, 12, 19, 46, 777459, tzinfo=utc), null=True, verbose_name=b'Processing till date'),
        ),
    ]
