# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20170620_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 27, 11, 37, 31, 383902, tzinfo=utc), null=True, verbose_name=b'Processing till date'),
        ),
    ]
