# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 04:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20170701_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 10, 4, 37, 35, 724032, tzinfo=utc), null=True, verbose_name=b'Processing till date'),
        ),
    ]
