# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 04:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_auto_20170710_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 18, 4, 39, 31, 579229, tzinfo=utc), null=True, verbose_name=b'Processing till date'),
        ),
    ]
