# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0102_auto_20170808_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.FloatField(blank=True, default=0, verbose_name='Vat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 16, 10, 12, 39, 983007, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
