# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0104_auto_20170809_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 16, 12, 57, 16, 750986, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
