# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0106_auto_20170810_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 17, 6, 37, 36, 331308, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
