# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0138_auto_20170822_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 8, 29, 10, 1, 19, 788347, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
