# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0149_auto_20170906_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 13, 4, 35, 8, 885826, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
