# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0152_auto_20170906_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_processing_date_till',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 9, 15, 8, 58, 1, 696739, tzinfo=utc), null=True, verbose_name='Processing till date'),
        ),
    ]
