# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0015_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(null=True, verbose_name='Deleivery date')),
                ('delivery_time', models.TimeField(null=True, verbose_name='Delivaery time')),
                ('total_price', models.FloatField(null=True, verbose_name='Price')),
                ('qty', models.IntegerField(null=True, verbose_name='qty')),
                ('user_status', models.IntegerField(null=True, verbose_name='Guest')),
                ('lunchbox_id', models.IntegerField(null=True, verbose_name='Lunchbox')),
                ('lunhbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.Lunchbox', verbose_name='Lunchbox')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
