# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carthandler', '0004_auto_20170717_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_time',
            field=models.TimeField(null=True, verbose_name='Delivery time'),
        ),
    ]
